[build]
  command = "corepack enable && corepack prepare pnpm@9.14.4 --activate && pnpm install --frozen-lockfile && NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--production=false"

[context.production.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"
  VITE_LOG_LEVEL = "warn"
  DEFAULT_NUM_CTX = "32768"
