[build]
  command = "npm install -g pnpm@9.14.4 && pnpm install --frozen-lockfile && NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--production=false"

[context.production.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"
